[project]
name = "marimo-1ere-explo-duckdb"
version = "0.1.0"
description = "1Ã¨re explo pour dÃ©couvrir DuckDB ðŸ¦† Ã  l'aide des donnÃ©es bixi ðŸš² & Marimo"
readme = "README.md"
authors = ["Antoine Giraud"]
requires-python = ">=3.13"
dependencies = [
    "marimo[sql]>=0.19.6",
    "folium>=0.20.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]
